id: f8c2fe81a94e443db22735879710ad82
initial_creation_type: ocr
source_metadata:
  volumes:
    de1ddc45083145bb8a4054778a0e1a81:
      base_file: v081.txt
      image_group_id: I1PD95927
      title: ''
      total_pages: 1630
      volume_number: 82
